### ISSUE TITLE
Cannot Resolve React-Rounded-Image

### ISSUE THREAD

**Issue by jganobsik** [AmineVolk/react-rounded-image#1]
The npm package appears to be broken. When building, the following error occurs: Module not found: Can't resolve 'react-rounded-image' in '/path/to/component'. Additional details:

Import statement: import ReactRoundedImage from 'react-rounded-image';

occurs both locally and via netlify build tools

**Comment by AmineVolk** [comment]
thanks for the issus @jganobsik ,
the problem was with the last update, but now it works fine
you just have to run : npm install react-rounded-image@2.0.10
